baseURL = 'https://paiinxz.github.io/'
languageCode = 'en-us'
title = 'Paiinxz'
theme = "LoveIt"
enableEmoji = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Writeups"
    url = "/writeups/"
    weight = 2

  [[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 3

  [[menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 4

[params]
  dateFormat = "02-01-2006"
  title = "Paiinxz"
  description = "Cybersecurity student and CTF player."

# Header config
[params.header]
  desktopMode = "fixed"
  mobileMode = "auto"

[params.header.title]
  logo = "https://avatars.githubusercontent.com/u/192268670?v=4"
  name = "Paiinxz"
  typeit = false
